// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhpuncdpkxsqeqghlwfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVocHVuY2Rwa3hzcWVxZ2hsd2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDE2NjMsImV4cCI6MjA1OTUxNzY2M30.k5T1gdTHIAw0h9HQvO4LRSv_GNPwQWwOHs8HkUSSZ0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);